os: linux
dist: trusty
language: c
compiler:
  - gcc

addons:
  apt:
    packages:
      - gcc-multilib
      - gcc
      - g++
      - autoconf
      - pkg-config
      - make
      - automake
      - bzip2
      - git

before_install:
   - echo "$PWD"
   - ( cd "$HOME"; wget -q -O - https://repo.turris.cz/omnia/OpenWrt-SDK-mvebu_gcc-4.8-linaro_musl-1.1.15_eabi.Linux-x86_64.tar.bz2 | bzip2 -d | tar -xf -; mv OpenWrt-SDK-mvebu* openwrt-sdk-omnia; wget -q -O - https://repo.turris.cz/turris/OpenWrt-SDK-mpc85xx-p2020-nand_gcc-4.8-linaro_uClibc-0.9.33.2.Linux-x86_64.tar.bz2 | bzip2 -d | tar -xf -; mv OpenWrt-SDK-mpc85xx* openwrt-sdk-turris;)

script:
  - echo "$PWD"
  - export SRC_PATH="$PWD"
  - cd "$HOME/openwrt-sdk-omnia"
  - echo "src-cpy siot $SRC_PATH" > feeds.conf
  - ./scripts/feeds update
  - ./scripts/feeds install -a
  - echo "src-git packages https://github.com/openwrt/packages.git^3a2c97600f051ba47f9aa83a121f3de09f567480" > feeds.conf
  - ./scripts/feeds update packages poco
  - ./scripts/feeds install -p packages poco
  - ./scripts/feeds update packages libloragw
  - ./scripts/feeds install -p packages libloragw
  - echo "src-git turrispackages https://gitlab.labs.nic.cz/turris/turris-os-packages.git^6b0685fce4816e5c20cd0f6eacf5e37166c87c74" > feeds.conf
  - ./scripts/feeds update turrispackages glib2
  - ./scripts/feeds install -p turrispackages glib2
  - make -j8 && { mkdir -p $HOME/dist-pkgs/turris-omnia; cp -r bin/*/packages $HOME/dist-pkgs/turris-omnia; true;} || make -j1 V=s
  - cd "$HOME/openwrt-sdk-turris"
  - echo "src-cpy siot $SRC_PATH" > feeds.conf
  - ./scripts/feeds update
  - ./scripts/feeds install -p siot nemea-ipfixprobe
  - make -j8 && { mkdir -p $HOME/dist-pkgs/turris; cp -r bin/*/packages $HOME/dist-pkgs/turris; true; } || make -j1 V=s

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: $HOME/dist-pkgs
  github_token: $GITHUB_TOKEN
  target_branch: turris-packages-devel
  on:
    branch: devel

