#!/bin/sh /etc/rc.common
# NEMEA flow_meter
# Copyright (C) 2016 CESNET

#
# How to use profiles:
# /etc/init.d/flow_meter start         - start all enabled profiles
# /etc/init.d/flow_meter start A B C   - stop all running profiles and start A, B and C profiles only
# /etc/init.d/flow_meter stop          - stop all profiles
# /etc/init.d/flow_meter stop A C      - stop A and C profiles only
# /etc/init.d/flow_meter enable        - start all enabled profiles on startup
# /etc/init.d/flow_meter disable       - disable all profiles on startup
# /etc/init.d/flow_meter restart       - stop and start all enabled profiles
# /etc/init.d/flow_meter reload        - stop and start all enabled profiles
#

START=50
STOP=50

USE_PROCD=1

CONFIG_FILE=flow_meter
BIN_FILE=/usr/bin/nemea/flow_meter

. /lib/functions.sh

start_profile()
{
   local PROFILE="$1"
   local OPTION="$2"

   config_get INTERFACE          "$PROFILE"  interface         ""
   config_get PLUGINS            "$PROFILE"  plugins           ""
   config_get IFC_SPEC           "$PROFILE"  ifcspec           ""
   config_get RESPAWN            "$PROFILE"  respawn           ""
   config_get RESPAWN_THRESHOLD  "$PROFILE"  respawn_threshold ""
   config_get RESPAWN_TIMEOUT    "$PROFILE"  respawn_timeout   ""
   config_get RESPAWN_RETRY      "$PROFILE"  respawn_retry     ""
   config_get CORE               "$PROFILE"  core              ""
   config_get ENABLED            "$PROFILE"  enabled           ""

   [ "${ENABLED:-0}" -eq 0 -a "$OPTION" == "only_enabled" ] && return

   logger -p daemon.notice -t flow_meter "starting instance with profile $PROFILE"

   procd_open_instance "$PROFILE"
   procd_set_param command "$BIN_FILE" -I "$INTERFACE" -p "${PLUGINS:-basic}" -i "$IFC_SPEC"
   [ "${RESPAWN:-0}" -eq 1 ] && procd_set_param respawn "${RESPAWN_THRESHOLD:-3600}" "${RESPAWN_TIMEOUT:-5}" "${RESPAWN_RETRY:-5}"
   procd_set_param limits core="${CORE:-0}"
   procd_set_param stdout 1
   procd_set_param stderr 1
   procd_close_instance
}

start_service()
{
   config_load "$CONFIG_FILE"

   if [ $# -eq 0 ]; then
      # start all (enabled) profiles
      config_foreach start_profile profile only_enabled
   else
      # start only specified profiles
      for i in "$@"; do
         start_profile "$i"
      done
   fi
}

