#!/bin/sh /etc/rc.common
# ipfixprobe, IPFIX flow exporter
# Copyright (C) 2022 CESNET

#
# How to use:
# /etc/init.d/ipfixprobe start         - start all enabled profiles
# /etc/init.d/ipfixprobe stop          - stop all profiles
# /etc/init.d/ipfixprobe enable        - start all enabled profiles on startup
# /etc/init.d/ipfixprobe disable       - disable all profiles on startup
# /etc/init.d/ipfixprobe restart       - stop and start all enabled profiles
# /etc/init.d/ipfixprobe reload        - stop and start all enabled profiles
#

START=50
STOP=50

USE_PROCD=1

NAME=ipfixprobe
PROG=/usr/bin/ipfixprobe

validate_section_ipfixprobe()
{
    uci_load_validate ipfixprobe ipfixprobe "$1" "$2" \
        'interfaces:list(string)' \
        'plugins:list(string)' \
        'ipfix_host:host:127.0.0.1' \
        'ipfix_port:port:4739' \
        'ipfix_udp:bool:1' \
        'cache_size:integer' \
        'cache_line:integer' \
        'active_timeout:integer' \
        'inactive_timeout:integer' \
        'link:integer' \
        'dir:integer' \
        'split_biflow:bool:0' \
        'ipfix_mtu:integer:1452' \
        'respawn:bool:1' \
        'respawn_threshold:integer:3600' \
        'respawn_timeout:integer:5' \
        'respawn_retry:integer:5' \
        'core:bool:0' \
        'enabled:bool:0'
}

handle_interface() {
    local ifc="$1"
    local blocks="$2"
    local pktinblock="$3"
    procd_append_param command -i "raw;i=$ifc;p=${pktinblock};b=${blocks}"
}

handle_plugins() {
    local plugin="$1"
    procd_append_param command -p "$plugin"
}

ipfixprobe_profile()
{
   local PROFILE="$1"

   if [ "$enabled" -eq 0 ]; then
      logger -p daemon.notice -t ipfixprobe "ipfixprobe profile $PROFILE disabled"
      return 1
   else
      logger -p daemon.notice -t ipfixprobe "ipfixprobe profile $PROFILE enabled"
   fi

   procd_open_instance "$PROFILE"

   procd_set_param command "$PROG"

   config_list_foreach "$PROFILE"   interfaces   handle_interface     "${raw_blocks:-2}" "${raw_packetsinblock:-10}"
   config_list_foreach "$PROFILE"   plugins     handle_plugins	     ""

   [ "${ipfix_udp:-0}" -eq 1 ] && UDP_PARAM=";u"
   [ "${split_biflow:-0}" -eq 1 ] && SPLIT_PARAM=";S"

   procd_append_param command -o "ipfix;h=$ipfix_host;p=${ipfix_port:-4739};I=${link:-0};d=${dir:-0}$UDP_PARAM;m=${ipfix_mtu:-1458}"
   procd_append_param command -s "cache;s=${cache_size:-10};l=${cache_line:-2};a=${active_timeout:-300};i=${inactive_timeout:-30}$SPLIT_PARAM"

   procd_set_param limits core="${core:-0}"
   procd_set_param stdout 1
   procd_set_param stderr 1
   procd_close_instance
}

start_service()
{
   config_load "$NAME"
   config_foreach validate_section_ipfixprobe profile ipfixprobe_profile
}

service_triggers() {
   procd_add_reload_trigger "$NAME"
   procd_add_validation validate_section_ipfixprobe
}

