#!/bin/sh /etc/rc.common
# NEMEA flow_meter
# Copyright (C) 2016 CESNET

#
# How to use profiles:
# /etc/init.d/flow_meter start         - start all enabled profiles
# /etc/init.d/flow_meter start A B C   - stop all running profiles and start A, B and C profiles only
# /etc/init.d/flow_meter stop          - stop all profiles
# /etc/init.d/flow_meter stop A C      - stop A and C profiles only
# /etc/init.d/flow_meter enable        - start all enabled profiles on startup
# /etc/init.d/flow_meter disable       - disable all profiles on startup
# /etc/init.d/flow_meter restart       - stop and start all enabled profiles
# /etc/init.d/flow_meter reload        - stop and start all enabled profiles
#

START=50
STOP=50

USE_PROCD=1

CONFIG_FILE=flow_meter
BIN_FILE=/usr/bin/nemea/flow_meter

. /lib/functions.sh

start_profile()
{
   local PROFILE="$1"
   local OPTION="$2"

   config_get INTERFACE          "$PROFILE"  interface         ""
   config_get PLUGINS            "$PROFILE"  plugins           ""
   config_get TRAP_IFC_SPEC      "$PROFILE"  trap_ifc_spec     ""
   config_get IPFIX_COLLECTOR    "$PROFILE"  ipfix_collector   ""
   config_get IPFIX_ENABLE       "$PROFILE"  ipfix_enable      ""
   config_get IPFIX_UDP          "$PROFILE"  ipfix_udp         ""
   config_get CACHE_SIZE         "$PROFILE"  cache_size        ""
   config_get TIMEOUTS           "$PROFILE"  timeouts          ""
   config_get LINK               "$PROFILE"  link              ""
   config_get DIR                "$PROFILE"  dir               ""
   config_get RESPAWN            "$PROFILE"  respawn           ""
   config_get RESPAWN_THRESHOLD  "$PROFILE"  respawn_threshold ""
   config_get RESPAWN_TIMEOUT    "$PROFILE"  respawn_timeout   ""
   config_get RESPAWN_RETRY      "$PROFILE"  respawn_retry     ""
   config_get CORE               "$PROFILE"  core              ""
   config_get ENABLED            "$PROFILE"  enabled           ""

   local EXPORTER="-i"
   local EXPORTER_PARAM="$TRAP_IFC_SPEC"

   [ "${ENABLED:-0}" -eq 0 -a "$OPTION" == "only_enabled" ] && return
   [ "${IPFIX_ENABLE:-0}" -eq 1 ] && { EXPORTER="-x"; EXPORTER_PARAM="$IPFIX_COLLECTOR"; }
   [ "${IPFIX_UDP:-0}" -eq 1 ] && UDP_PARAM="-u"

   logger -p daemon.notice -t flow_meter "starting instance with profile $PROFILE"

   procd_open_instance "$PROFILE"
   procd_set_param command "$BIN_FILE" -I "$INTERFACE" -p "${PLUGINS:-basic}" "$EXPORTER" "$EXPORTER_PARAM" -s "${CACHE_SIZE:-default}" -t "${TIMEOUTS:-default}" -L "${LINK:-0}" -D "${DIR:-0}" "$UDP_PARAM"
   [ "${RESPAWN:-1}" -eq 1 ] && procd_set_param respawn "${RESPAWN_THRESHOLD:-3600}" "${RESPAWN_TIMEOUT:-5}" "${RESPAWN_RETRY:-5}"
   procd_set_param limits core="${CORE:-0}"
   procd_set_param stdout 1
   procd_set_param stderr 1
   procd_close_instance
}

start_service()
{
   config_load "$CONFIG_FILE"

   if [ $# -eq 0 ]; then
      # start all (enabled) profiles
      config_foreach start_profile profile only_enabled
   else
      # start only specified profiles
      for i in "$@"; do
         start_profile "$i"
      done
   fi
}

